apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs 
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: nginx-pod 
      labels:
        env: production 
    spec:
      container   
